---
- name: Copy global gitignore
  copy:
    src: gitignore_global
    dest: "{{ desktop_user_vars.dir }}/.gitignore_global"
- name: Configure user local git configs
  template:
    src: gitconfig
    dest: "{{ desktop_user_vars.dir }}/.gitconfig"
